<?php
    /** @var \Mastering\SampleModule\Block\Hello $block */

    echo '</br>Welcome Magento Redis</br>';
    $redis = new Redis();
    $redis->connect('127.0.0.1', 6379);

    echo $redis->ping();
    echo '</br>Hello hacker</br>';

    $push = isset($_GET['push']) ? $_GET['push'] : false;
    $pop = isset($_GET['pop']) ? $_GET['pop'] : false;

    if ($push) {
        echo 'Run push: '.$push;
        $redis->rPush('char', $push);
    } else if ($pop) {
        echo 'Run pop: '.$pop;
        $redis->lPop('char');
    }

    echo '</br>';
    print_r($redis->lRange('char', 0, -1));





//    $ordersNew = $block-> getAllOrders() -> getData();

//    echo '<pre>';
//    print_r($ordersNew);
//    echo '</pre>';

    // echo '<pre>';
    // print_r(gettype($ordersNew));
    // print_r(get_class_methods($ordersNew));
    // print_r(get_object_vars($ordersNew));
    // echo '<pre>';

    // echo '<pre>';
//    print_r($block-> getAllOrders()->getData());
        // foreach ($block->getAllOrders() as $order) {
        //     echo '</br>';
        //     print_r($order->getData());
        //     $order->setData('sent_to_oracle', 0);
        //     $order->save();
        // }
    // echo '</pre>';

//     $datanew = $block-> getAllOrders() -> getData()[2];
//    echo '<pre>';
//     print_r(gettype($datanew));
//     print_r(get_class_methods($datanew));
//     print_r(get_object_vars($datanew));
//    echo '</pre>';
//
//    $order = 1;
//    if (isset($_GET['order'])) {
//        $order = $_GET['order'];
//    }
//    $data = $block->getOrderById($order);

//    echo '</br>orders</br>';
//    echo '<pre>';
//    print_r($data->getData());
//    $class_mt = get_class_methods($data);
//    print_r($class_mt);
//    echo '</pre>';
//
//    echo '</br>getShippingAddress</br>';
//    print_r($data->getShippingAddress()->getData());
//
//    echo '</br>getBillingAddress</br>';
//    print_r($data->getBillingAddress()->getData());
//
//    echo '</br>getAllItems</br>';
//    $orderItems = $data->getAllItems();
//    foreach ($orderItems as $item){
//        echo '</br>';
//        print_r($item->getQtyOrdered());
//        print_r($item->getDescription());
//        print_r($item->getName());
//        print_r($item->getPrice());
//    }
    
//     echo '</br></br>';


//    echo '<pre>';
//
//    foreach($ordersNew as $order) {
//        $result = $block->getOrderById($order['entity_id']);
//        // print_r($result->getData());
//        $result->setData('sent_to_oracle', 0);
//        $result->save();
//
//        $orderData = $result->getData();
//        $shippingAddress = $result->getShippingAddress()->getData();
//        $billingAddress = $result->getBillingAddress()->getData();
//        $orderData['shippingAddress'] = $shippingAddress;
//        $orderData['billingAddress'] = $billingAddress;
//
//        $allItems = [];
//        $allItemsResult = $result->getAllItems();
//        foreach($allItemsResult as $item) {
//            // var_dump($item);
//            array_push($allItems, $item->getData());
//            print_r(gettype($item));
//            print_r(get_class_methods($item));
//            print_r(get_object_vars($item));
//        }
//        $orderData['allItems'] = $allItems;
//
//        echo "<script>console.log(".json_encode($orderData).");</script>";
//    }
//
//    echo '</pre>';


