<?php
    /** @var \Mastering\SampleModule\Block\Hello $block */
?>

<?php foreach ($block -> getItems() as $item): ?>
    </br> <?php echo $item->getName(); ?>  ;  <?php echo $item->getDescription(); ?>
<?php endforeach; ?>

<?php
    echo '</br></br>';

    // print_r($block-> getAllOrders()->getData());

    $order = 1;
    if (isset($_GET['order'])) {
        $order = $_GET['order'];
    }
    $data = $block->getOrderById($order);

    echo '</br></br>';
    print_r($data->getData());

    echo '</br></br>';
    print_r($data->getShippingAddress()->getData());
    
    echo '</br></br>';
    print_r($data->getBillingAddress()->getData());
    
    echo '</br></br>';


